### ISSUE TITLE
Are there any plans to release a PyTorch version?

### ISSUE THREAD

**Issue by IDKiro** [moabarar/qna#3]
It is an amazing job!

I implemented a PyTorch  version to work with my previous code, but it doesn't seem to be stably trained (always nan), and I believe it is likely that I misunderstood or missed some implementation details.

I wanted to ask if you have any plans to release a PyTorch version.

**Comment by moabarar** [comment]
Thank you for your interest in our work! 

All our models were trained using Jax on a TPU, and I don't have access to a GPU cluster to test my code on it with PyTorch. I will try to convert our models to PyTorch and upload inference code, but I am currently busy with other obligations, so please expect delays.

One thing that I found to stabilise the training is to always normalize the query vectors before using them:
https://github.com/moabarar/qna/blob/1f8e8e3d395d2fb061b90a4e4ef061b2f5fef4ec/layers/qna.py#L19

Hope this could resolve your issue, if not feel free to ask any other question regarding the implementation.

**Comment by IDKiro** [comment]
Thank you very much for your answer, I will try it

**Comment by Vladimir2506** [comment]
> Thank you very much for your answer, I will try it

@IDKiro Hello, have you managed to fix the training stability problem?
