### ISSUE TITLE
A QNA implementation in Scenic?

### ISSUE THREAD

**Issue by MostafaDehghani** [moabarar/qna#4]
Hi, 
I really enjoyed reading the code here and it's super cool that you developed in JAX.  I wanted to suggest porting your model to Scenic as well if you got time at some point and hopefully we can start playing with it internally and maybe even scale it up.
Let me know if you wanted to do this. Happy to chat.
Awesome work anyways and looking forward to the follow ups :)

**Comment by moabarar** [comment]
Hi Mostafa, 

Thanks for your message! I would like that sure,  I already worked with Scenic and trained DETR with QnA-ViT as a backbone, your library is awesome! 
Let me know how to reach-out.
Closing the issue for now, feel free to re-open if needed.
